project_id = "sodium-pager-461309-p3"
region     = "us-central1"
zone       = "us-central1-a"
credentials_path = "../keys/terraform-deployer-key.json"
machine_type     = "e2-medium"
bucket_name = "ml-artifacts-tutorial"
blob_name   = "models/latest.joblib"
