apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-api
  template:
    metadata:
      labels:
        app: serving-api
    spec:
      containers:
        - name: serving-api
          image: us-central1-docker.pkg.dev/sodium-pager-461309-p3/serving/inference-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/key.json
          volumeMounts:
            - name: gcp-key
              mountPath: /app/key.json
              subPath: key.json
      volumes:
        - name: gcp-key
          secret:
            secretName: gcp-key-secret
