apiVersion: v1
kind: Service
metadata:
  name: training-service-api-service
spec:
  type: LoadBalancer
  selector:
    app: training-service-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
