apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  labels:
    app: mlflow
spec:
  type: LoadBalancer
  selector:
    app: mlflow
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
