name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      serving: ${{ steps.filter.outputs.serving }}
      training_service: ${{ steps.filter.outputs.training_service }}
      ml_pipeline: ${{ steps.filter.outputs.ml_pipeline }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            serving:
              - 'serving/**'
            training_service:
              - 'training_service/**'
            ml_pipeline:
              - 'ml_pipeline/**'

  deploy-serving:
    needs: filter-changes
    if: needs.filter-changes.outputs.serving == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.TIME_ZONE }}-docker.pkg.dev

      - name: Build Docker image for serving
        run: |
          docker build -t ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/serving-repo/serving-api:latest ./serving

      - name: Push Docker image for serving
        run: |
          docker push ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/serving-repo/serving-api:latest

      - name: Get GKE credentials for serving cluster
        run: |
          gcloud container clusters get-credentials ${{ secrets.SERVING_CLUSTER }} --zone ${{ secrets.TIME_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Confirm current context (safety check)
        run: |
          echo "Current context:"
          kubectl config current-context
          if [[ "$(kubectl config current-context)" != "gke_sodium-pager-461309-p3_us-central1-a_serving-cluster" ]]; then
            echo "❌ Wrong context! Aborting."
            exit 1
          fi

      - name: Deploy serving to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Rollout restart serving deployment
        run: |
          kubectl rollout restart deployment/serving-api
          kubectl rollout status deployment/serving-api

  deploy-training-service:
    needs: filter-changes
    if: needs.filter-changes.outputs.training_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Build Docker image for training service
        run: |
          docker build -t ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/training-service-repo/training-service:latest ./training_service

      - name: Push Docker image for training service
        run: |
          docker push ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/training-service-repo/training-service:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.TRAINING_CLUSTER }} --zone ${{ secrets.TIME_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Confirm current context (safety check)
        run: |
          echo "Current context:"
          kubectl config current-context
          if [[ "$(kubectl config current-context)" != "gke_sodium-pager-461309-p3_us-central1-a_serving-cluster" ]]; then
            echo "❌ Wrong context! Aborting."
            exit 1
          fi

      - name: Deploy training service to GKE
        run: |
          kubectl apply -f k8s/deployment_training_service.yaml
          kubectl apply -f k8s/service_training_service.yaml

      - name: Rollout restart training service deployment
        run: |
          kubectl rollout restart deployment/training-service-api
          kubectl rollout status deployment/training-service-api

  deploy-training-pipeline:
    needs: filter-changes
    if: needs.filter-changes.outputs.ml_pipeline == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Build Docker image for training pipeline
        run: |
          docker build -t ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/training-repo/training:latest ./ml_pipeline

      - name: Push Docker image for training pipeline
        run: |
          docker push ${{ secrets.TIME_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/training-repo/training:latest
