name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_TITANIC_PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_TITANIC_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_TITANIC_PROJECT_ID }}/titanic-repo/titanic-api:latest ./api

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_TITANIC_PROJECT_ID }}/titanic-repo/titanic-api:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.TITANIC_CLUSTER }} --zone us-central1-a

    - name: Replace project ID in deployment.yaml
      run: |
        sed "s|GCP_PROJECT_ID|${{ secrets.GCP_TITANIC_PROJECT_ID }}|g" k8s/deployment.template.yaml > k8s/deployment.yaml

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
